### ISSUE TITLE
cfs.GCharts.uniGUI.Sydney.dpk(37): E2202 Package 'uniGUI27'

### ISSUE THREAD

**Issue by odyright** [JosepPages7/Delphi-GCharts#3]
Hi, thanks for your work. 
I'm facing that issue when i tried to install your package:
`[dcc32 Erreur fatale] cfs.GCharts.uniGUI.Sydney.dpk(37): E2202 Package 'uniGUI27' required not found`

![image](https://user-images.githubusercontent.com/4316506/199129037-4fe882f4-bf98-4cad-8816-4530d2864fdb.png)

**Comment by JosepPages7** [comment]
To install this component you need to have previously installed the library with the uniGUI components.
